services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes: 
      - mongodata:/data/db
    networks:
      - "nextone-network"
volumes:
  mongodata:
networks:
  nextone-network:
    driver: bridge
    name: nextone-network